name: CD

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release.yaml
    with:
      node-version: '20'
    secrets: inherit
