name: CD

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "[CD] Release packages"
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release.yaml
