name: CI

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  code-quality:
    name: "[CI] Code Quality"
    uses: ./.github/workflows/code-quality.yaml
  build:
    name: "[CI] Build packages"
    uses: ./.github/workflows/build.yaml
