name: Code Quality

on:
  workflow_call:      

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check for TypeScript errors
        run: pnpm ts-check
      - name: Check for formatting and linting errors
        run: pnpm biome ci .
      - name: Check for spelling errors
        run: pnpm spell-check
