name: Release

on:
  workflow_call:

jobs:
  release:
    # Prevent the job from running on forks
    if: github.repository == 'Henskelis/nh-poc'
    permissions:
      contents: write
      pull-requests: write
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Disable telemetry of Turborepo
        run: pnpm turbo telemetry disable
      - name: Setup npm authentication with a token
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Version and publish packages
        uses: changesets/action@v1
        with:
          title: Version packages
          commit: version packages
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
