name: Release

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use for building and releasing
        type: string
        required: true

jobs:
  release:
    # Prevent the job from running on forks
    if: github.repository == 'Henskelis/nh-poc'
    permissions:
      contents: write
      pull-requests: write
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Disable telemetry of Turborepo
        run: pnpm turbo telemetry disable
      - name: Version or build and publish packages
        uses: changesets/action@v1
        with:
          title: Version packages
          commit: version packages
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
